var mongoose = require('mongoose'),
    //Ingredient = require('mongoose').model('Ingredient'),
	Schema = mongoose.Schema;

var IngredientPriceSchema = new Schema({
    ingredient: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Ingredient',
        required: true
    },
    price: {
        type: Number,
        required: true
    }
});
mongoose.model('IngredientPrice', IngredientPriceSchema);

var VendorSchema = new Schema({
	name: {
		type: String,
		trim: true,
		unique: [true, "already exists"],
		required: true
	},
	contact: String,
	code: { // user input
	    type: String,
	    unique: true,
	    required: true,
	},
	codeUnique: { //auto generated by server
        type: String,
        unique: true,
        lowercase: true,
        required: true
    },
	//ingredients: [IngredientPriceSchema]

});

mongoose.model('Vendor', VendorSchema);
